apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-replay.backend.fullname" . }}
  labels:
    {{- include "incident-replay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "incident-replay.backend.fullname" . }}
